---
- name: install system updates for centos systems
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == "CentOS"

- name: install system updates for ubuntu systems
  apt: upgrade=dist update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install required packages
  package:
    name: ['sudo', 'iptables', 'docker.io', 'python3-docker']
    state: present

- name: install ctop to monitor containers
  get_url:
      url: https://github.com/bcicen/ctop/releases/download/v0.7.2/ctop-0.7.2-linux-amd64
      dest: /usr/local/bin/ctop
      mode: 0755
